services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8501:8501"
    environment:
      CHECKED_IPS_FILE: checked_ips.csv
      CHECKED_MAC_FILE: checked_mac.csv
    volumes:
      - .:/app